### ISSUE TITLE
feature request: plug other notifiers in

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sierkb/portsnotifier#1]
```
i'd especially be interested in having same functionality to check that my perl 
cpan modules are up 
to date.
```

Original issue reported on code.google.com by `gray.tri...@gmail.com` on 1 Jun 2007 at 4:13

**Comment by sierkb** [comment]
Closing this issue, since the plan of the original author to make it a general notifier platform has been abandoned  (as well as the whole project) by the original author, and so far it's not planned to pick up the idea in the future.
