### ISSUE TITLE
Source tarballs are not available for downloading (ideally from SourceForge.net servers)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sierkb/portsnotifier#2]
```
I am writing a Portfile for this application and would prefer to be able to use 
the source tarball 
corresponding to the code in the .dmg at SourceForge.net.
```

Original issue reported on code.google.com by `randall....@gmail.com` on 14 Jul 2007 at 10:02

**Comment by sierkb** [comment]
Closing this issue, since GitHub provides Zip and Tarball downloads of the source code for any branches or tags, defaulting to master, see also https://github.com/blog/12-tarball-downloads.
