### ISSUE TITLE
.dmg is Intel only?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sierkb/portsnotifier#3]
```
Mac OS X 10.4.10 / PowerPC G4:

The compiled code in the .dmg from sourceforge.net is not universal, but is 
instead Intel only, 
preventing it from running on PowerPC-based macs.
```

Original issue reported on code.google.com by `randall....@gmail.com` on 14 Jul 2007 at 10:04

**Comment by sierkb** [comment]
Closing this issue, since no downloadable .dmg with a prebuild binary is provided at this hosting platform (GitHub).
